import { Customer } from './customer';

export const CUSTOMERS: Customer[] = [
  { id: 1, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
  { id: 2, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
  { id: 3, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
  { id: 4, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
  { id: 5, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
  { id: 6, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
  { id: 7, name: 'Стройхолдингсевергруп', profile: 'Строительство', status: 'Переговоры', website: 'https://example.com', phone: '+7 (123) 456-78-90', address: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet', contactPerson: 'Иванов Иван Иванович', contactPersonPost: 'Начальник тендерного комитета', workPhone: '+7 (123) 456-78-90', mobilePhone: '+7 (123) 456-78-90', email: 'i.ivanov@example.com', comments: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, eveniet' },
];
